# Generated by Django 4.2.13 on 2024-06-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=True, null=True, verbose_name='زمان اضافه شدن'),
        ),
    ]
