# Generated by Django 4.0.5 on 2024-06-27 15:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(default=True, null=True, upload_to='Product_app/Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(default=True, null=True, upload_to='Poduct_app/category')),
                ('create_at', models.DateTimeField(default=datetime.datetime(2024, 6, 27, 15, 55, 25, 133234, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('used_for', models.CharField(max_length=60)),
                ('multivatins_type', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.BigIntegerField()),
                ('score', models.IntegerField()),
                ('image', models.ImageField(default=True, null=True, upload_to='Product_app/Product')),
                ('off_price', models.CharField(max_length=20, null=True)),
                ('descriptions', models.TextField()),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.brand')),
                ('category', models.ManyToManyField(to='Product.category')),
                ('specifications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.specifications')),
            ],
        ),
    ]
