# Generated by Django 4.0.5 on 2024-06-27 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 15, 55, 32, 402035, tzinfo=utc)),
        ),
    ]
